// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
//
// Renders the builtins reference page for the docs site from the builtin catalog, in MeTTa's own @doc-formal
// shape (item, type, description, parameters, return) — the TypeScript counterpart of hyperon's
// document-module / help-md!. Each entry is enriched by the interpreter's get-doc when a symbol is
// self-documenting: a MettaDoc adds its per-parameter and return descriptions, which the catalog alone does
// not carry. Anchors come from the one canonical slug function the hover's "Open docs" link uses, so an
// entry and the link that jumps to it never disagree.

import type { MettaDoc } from "../language-service/coreRuntime.js";
import { anchor } from "../server/docsLinks.js";
import type { DefinitionRecord } from "../server/types.js";
import { docDetailSections } from "./mettaDoc.js";

// One builtin plus any @doc-formal the interpreter surfaced for it (null when the symbol carries no @doc).
export interface BuiltinEntry {
  readonly def: DefinitionRecord;
  readonly doc: MettaDoc | null;
}

// The catalog's DefinitionKind maps onto three reference sections, in this order.
const GROUPS: readonly { readonly kind: string; readonly title: string }[] = [
  { kind: "macro", title: "Special forms and macros" },
  { kind: "type", title: "Type constructors" },
  { kind: "function", title: "Functions and operators" },
];

const INTRO = `# Builtins reference

Every builtin the language server knows: special forms, type constructors, and grounded functions.
Hovering a builtin in your editor links here to its entry. Punctuation operators (\`+\`, \`->\`) share the
top of each section; named builtins have their own anchor.

<img src="/assets/animations/divider-candy.svg" alt="" class="candy-divider" />`;

const GENERATED_NOTE =
  "<!-- Generated by scripts/generate-builtin-reference.mjs from the builtin catalog and the interpreter's\n     get-doc. Run `npm run docs:builtins` to regenerate. Do not edit by hand. -->";

// The signature to show in the ```metta``` fence, or null when there is nothing structural to show. A real
// call form (starts with `(`) is shown verbatim; an elementary type with only a placeholder signature is
// shown as its canonical `(: Name Type)` declaration.
function signatureFence(def: DefinitionRecord): string | null {
  const raw = def.signature?.raw ?? def.detail ?? "";
  if (raw.startsWith("(")) return raw;
  if (def.kind === "type") return `(: ${def.name} Type)`;
  return null;
}

// Operators (punctuation names that slug to an empty anchor) sort before named builtins within a section, and
// named builtins sort alphabetically — a stable, deterministic order independent of catalog insertion order.
function orderEntries(entries: readonly BuiltinEntry[]): BuiltinEntry[] {
  return [...entries].sort((a, b) => {
    const aNamed = anchor(a.def.name).length === 0 ? 0 : 1;
    const bNamed = anchor(b.def.name).length === 0 ? 0 : 1;
    if (aNamed !== bNamed) return aNamed - bNamed;
    return a.def.name.localeCompare(b.def.name);
  });
}

function renderEntry({ def, doc }: BuiltinEntry): string {
  const slug = anchor(def.name);
  const parts: string[] = [
    slug.length > 0 ? `### \`${def.name}\` {#${slug}}` : `### \`${def.name}\``,
  ];

  const fence = signatureFence(def);
  if (fence !== null) parts.push(`\`\`\`metta\n${fence}\n\`\`\``);

  // A hand-authored @doc description wins over the catalog blurb; otherwise the catalog's own documentation.
  const description =
    doc?.description && doc.description.length > 0 ? doc.description : def.documentation;
  if (description !== undefined && description.length > 0) parts.push(description);
  if (def.deprecated === true) parts.push("_Deprecated._");

  // The same parameter/return rendering the hover uses, so a documented symbol reads identically in both.
  if (doc !== null) parts.push(...docDetailSections(doc));
  return parts.join("\n\n");
}

// The full builtins reference page. Deterministic: same entries in, byte-identical markdown out, so a drift
// test can assert the committed page equals a fresh render.
export function renderBuiltinReference(entries: readonly BuiltinEntry[]): string {
  const sections: string[] = [GENERATED_NOTE, INTRO];
  for (const { kind, title } of GROUPS) {
    const group = orderEntries(entries.filter((entry) => entry.def.kind === kind));
    if (group.length === 0) continue;
    sections.push(`## ${title}`);
    for (const entry of group) sections.push(renderEntry(entry));
  }
  return `${sections.join("\n\n")}\n`;
}
