// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
//
// Builds and renders the generated MeTTa API reference. The extractor reads the analyzer's indexed
// definitions, asks CoreRuntime for the same @doc-formal records hovers use, and attaches TypeScript host
// operations from HostTypeService. The JSON graph is the boundary; Markdown and VitePress sidebar files are
// derived from that graph.

import type { Range } from "vscode-languageserver-types";
import { CoreRuntime, type MettaDoc } from "../language-service/coreRuntime.js";
import { normalizeUri, uriToPath } from "../language-service/index.js";
import type { Analyzer } from "../server/analyzer.js";
import type { HostBinding, HostBindingKind } from "../server/bridge/hostBridge.js";
import { anchor } from "../server/docsLinks.js";
import type { DefinitionRecord, DocumentIndex } from "../server/types.js";
import { docDetailSections } from "./mettaDoc.js";

export type MettaDocSymbolKind =
  | "function"
  | "macro"
  | "type"
  | "constant"
  | "space"
  | "binding"
  | "module";

export interface MettaDocIndex {
  readonly schemaVersion: 1;
  readonly generatedAt: string;
  readonly sourceFingerprint: string;
  readonly modules: readonly MettaModuleDoc[];
  readonly hostOperations: readonly HostOperationDoc[];
}

export interface MettaModuleDoc {
  readonly name: string;
  readonly slug: string;
  readonly sourceUri: string;
  readonly sourcePath: string;
  readonly imports: readonly string[];
  readonly symbols: readonly MettaSymbolDoc[];
}

export interface MettaSymbolDoc {
  readonly name: string;
  readonly anchor: string;
  readonly kind: MettaDocSymbolKind;
  readonly type: string;
  readonly signature: string;
  readonly doc: MettaDoc | null;
  readonly fallbackDoc: string | null;
  readonly definitionUri: string;
  readonly sourcePath: string;
  readonly range: Range;
  readonly hostOperation: string | null;
}

export interface HostOperationDoc {
  readonly name: string;
  readonly slug: string;
  readonly hostKind: HostBindingKind;
  readonly tsSignature: string;
  readonly mettaType: string;
  readonly docs: string;
  readonly origin: string;
  readonly sourceUri: string;
  readonly sourcePath: string;
  readonly definitionUri: string | null;
  readonly definitionRange: Range | null;
}

export interface BuildMettaDocIndexOptions {
  readonly analyzer: Analyzer;
  readonly runtime?: CoreRuntime;
  readonly workspaceRootUri?: string;
  readonly sourceRootUri?: string;
  readonly generatedAt?: string;
  readonly hostBindings?: readonly HostBinding[];
}

const GENERATED_AT = "deterministic";
const GENERATED_NOTE =
  "<!-- Generated by scripts/generate-metta-docs.mjs from Analyzer, CoreRuntime get-doc, and HostTypeService.\n     Run `npm run docs:metta` to regenerate. Do not edit by hand. -->";

const SYMBOL_KIND_ORDER: readonly MettaDocSymbolKind[] = [
  "type",
  "macro",
  "function",
  "constant",
  "space",
  "binding",
  "module",
];

const SYMBOL_KIND_TITLES: Readonly<Record<MettaDocSymbolKind, string>> = {
  type: "Types",
  macro: "Macros",
  function: "Functions",
  constant: "Constants",
  space: "Spaces",
  binding: "Bindings",
  module: "Modules",
};

function rangeKey(range: Range): string {
  return `${range.start.line}:${range.start.character}:${range.end.line}:${range.end.character}`;
}

function stableHash(text: string): string {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index++)
    hash = Math.imul(hash ^ text.charCodeAt(index), 16777619);
  return `${text.length}-${(hash >>> 0).toString(16)}`;
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function pathFromUri(uri: string): string {
  return uriToPath(uri) ?? uri;
}

function sourcePathFromUri(uri: string, sourceRootUri: string | undefined): string {
  if (sourceRootUri === undefined) return pathFromUri(uri);
  return relativeUriPath(uri, sourceRootUri);
}

function stripMettaExtension(path: string): string {
  return path.replace(/\.metta$/i, "");
}

function normalizePathSeparators(path: string): string {
  return path.replaceAll("\\", "/");
}

function basename(path: string): string {
  const normalized = normalizePathSeparators(path);
  const index = normalized.lastIndexOf("/");
  return index === -1 ? normalized : normalized.slice(index + 1);
}

function stripLeadingPathSeparators(path: string): string {
  let index = 0;
  while (index < path.length && (path[index] === "/" || path[index] === ".")) index += 1;
  return path.slice(index);
}

function stripTrailingSlashes(uri: string): string {
  let end = uri.length;
  while (end > 0 && uri[end - 1] === "/") end -= 1;
  return uri.slice(0, end);
}

function appendCollapsedDash(parts: string[]): void {
  const last = parts.at(-1);
  if (last !== undefined && last !== "-" && last !== "/") parts.push("-");
}

function appendCollapsedSlash(parts: string[]): void {
  while (parts.at(-1) === "-") parts.pop();
  if (parts.length > 0 && parts.at(-1) !== "/") parts.push("/");
}

function relativeUriPath(uri: string, rootUri: string | undefined): string {
  const normalized = normalizeUri(uri);
  if (rootUri !== undefined && normalized.startsWith(rootUri)) {
    const rest = stripLeadingPathSeparators(normalized.slice(rootUri.length));
    return decodeURIComponent(rest);
  }
  return basename(pathFromUri(normalized));
}

function slugify(value: string): string {
  const parts: string[] = [];
  const input = stripLeadingPathSeparators(normalizePathSeparators(value));
  for (const char of input) {
    const lower = char.toLowerCase();
    const code = lower.charCodeAt(0);
    const isAlpha = code >= 97 && code <= 122;
    const isDigit = code >= 48 && code <= 57;
    if (isAlpha || isDigit || lower === "_") parts.push(lower);
    else if (lower === "/") appendCollapsedSlash(parts);
    else appendCollapsedDash(parts);
  }
  while (parts.at(-1) === "-" || parts.at(-1) === "/") parts.pop();
  const base = parts.join("");
  return base.length > 0 ? base : "item";
}

function uniqueSlug(base: string, seen: Set<string>): string {
  let slug = base;
  let suffix = 2;
  while (seen.has(slug)) {
    slug = `${base}-${suffix}`;
    suffix += 1;
  }
  seen.add(slug);
  return slug;
}

function uniqueAnchorFor(name: string, seen: Set<string>): string {
  const base = anchor(name) || slugify(name);
  return uniqueSlug(base, seen);
}

function moduleName(uri: string, rootUri: string | undefined): string {
  return stripMettaExtension(relativeUriPath(uri, rootUri));
}

function sourceLine(range: Range): number {
  return range.start.line + 1;
}

function isLintConfig(index: DocumentIndex): boolean {
  return normalizePathSeparators(pathFromUri(index.uri)).endsWith("/lint.metta");
}

function normalizeRootUri(rootUri: string | undefined): string | undefined {
  if (rootUri === undefined || rootUri.length === 0) return undefined;
  return stripTrailingSlashes(normalizeUri(rootUri));
}

function preferredDefinition(defs: readonly DefinitionRecord[]): DefinitionRecord {
  return defs.find((def) => def.kind !== "type") ?? defs[0] ?? defStub();
}

function defStub(): DefinitionRecord {
  const zero = { line: 0, character: 0 };
  return {
    name: "",
    kind: "unknown",
    uri: "",
    range: { start: zero, end: zero },
    selectionRange: { start: zero, end: zero },
  };
}

function docFallback(defs: readonly DefinitionRecord[], primary: DefinitionRecord): string | null {
  const documented =
    primary.documentation ??
    defs.find((def) => def.documentation !== undefined)?.documentation ??
    null;
  return documented !== null && documented.trim().length > 0 ? documented : null;
}

function symbolKind(def: DefinitionRecord): MettaDocSymbolKind {
  if (def.kind === "unknown" || def.kind === "keyword") return "constant";
  if (def.kind === "type") {
    if (def.signature?.raw.startsWith("(->") === true) return "function";
    if (def.signature?.raw === "Type" || /^[A-Z]/u.test(def.name)) return "type";
    return "constant";
  }
  return def.kind;
}

function symbolType(def: DefinitionRecord, doc: MettaDoc | null): string {
  if (doc?.type && doc.type.length > 0) return doc.type;
  if (def.signature?.raw) return def.signature.raw;
  return def.detail ?? "";
}

function symbolSignature(def: DefinitionRecord, kind: MettaDocSymbolKind): string {
  if (def.signature) return `(: ${def.name} ${def.signature.raw})`;
  if (kind === "function" || kind === "macro") return def.detail ?? `(${def.name})`;
  if (kind === "type") return `(: ${def.name} Type)`;
  if (def.detail) return def.detail;
  return def.name;
}

function groupedDefinitions(index: DocumentIndex): DefinitionRecord[][] {
  const byName = new Map<string, DefinitionRecord[]>();
  for (const def of index.definitions) {
    if (def.name.length === 0 || def.exported === false) continue;
    const existing = byName.get(def.name) ?? [];
    existing.push(def);
    byName.set(def.name, existing);
  }
  return [...byName.values()].sort((a, b) => {
    const left = preferredDefinition(a);
    const right = preferredDefinition(b);
    const byKind =
      SYMBOL_KIND_ORDER.indexOf(symbolKind(left)) - SYMBOL_KIND_ORDER.indexOf(symbolKind(right));
    if (byKind !== 0) return byKind;
    const byName = left.name.localeCompare(right.name);
    if (byName !== 0) return byName;
    return rangeKey(left.range).localeCompare(rangeKey(right.range));
  });
}

function hostBindingDocs(
  bindings: readonly HostBinding[],
  sourceRootUri: string | undefined,
): HostOperationDoc[] {
  const seen = new Set<string>();
  return bindings.map((binding) => {
    const slug = uniqueSlug(slugify(binding.name), seen);
    const definitionUri = binding.definition?.uri ?? null;
    const sourcePath =
      definitionUri === null ? binding.origin : sourcePathFromUri(definitionUri, sourceRootUri);
    return {
      name: binding.name,
      slug,
      hostKind: binding.kind,
      tsSignature: binding.signature.label,
      mettaType: binding.signature.mettaArrow,
      docs: binding.signature.documentation ?? "",
      origin: binding.origin,
      sourceUri: sourcePath,
      sourcePath,
      definitionUri: definitionUri === null ? null : sourcePath,
      definitionRange: binding.definition?.range ?? null,
    };
  });
}

function symbolDocsForModule(
  index: DocumentIndex,
  runtime: CoreRuntime,
  analyzer: Analyzer,
  sourceRootUri: string | undefined,
  hostByName: ReadonlyMap<string, HostOperationDoc>,
): MettaSymbolDoc[] {
  const context = analyzer.declarationContextForDocs(index.uri);
  const anchors = new Set<string>();
  return groupedDefinitions(index).map((defs) => {
    const primary = preferredDefinition(defs);
    const docResult = runtime.getDoc(context, primary.name);
    const doc = docResult.isOk() ? docResult.value : null;
    const sourcePath = sourcePathFromUri(primary.uri, sourceRootUri);
    return {
      name: primary.name,
      anchor: uniqueAnchorFor(primary.name, anchors),
      kind: symbolKind(primary),
      type: symbolType(primary, doc),
      signature: symbolSignature(primary, symbolKind(primary)),
      doc,
      fallbackDoc: doc === null ? docFallback(defs, primary) : null,
      definitionUri: sourcePath,
      sourcePath,
      range: primary.range,
      hostOperation: hostByName.get(primary.name)?.slug ?? null,
    };
  });
}

function moduleDocs(
  analyzer: Analyzer,
  runtime: CoreRuntime,
  rootUri: string | undefined,
  sourceRootUri: string | undefined,
  hostOperations: readonly HostOperationDoc[],
): MettaModuleDoc[] {
  const seen = new Set<string>();
  const hostByName = new Map(hostOperations.map((operation) => [operation.name, operation]));
  const modules: MettaModuleDoc[] = [];
  for (const uri of analyzer.indexedUris()) {
    const index = analyzer.getDocument(uri);
    if (index === undefined || isLintConfig(index)) continue;
    const name = moduleName(index.uri, rootUri);
    const slug = uniqueSlug(slugify(name), seen);
    const sourcePath = sourcePathFromUri(index.uri, sourceRootUri);
    modules.push({
      name,
      slug,
      sourceUri: sourcePath,
      sourcePath,
      imports: [...new Set(index.imports.map((imp) => imp.rawPath))].sort(),
      symbols: symbolDocsForModule(index, runtime, analyzer, sourceRootUri, hostByName),
    });
  }
  return modules.sort((a, b) => a.name.localeCompare(b.name));
}

export function buildMettaDocIndex(options: BuildMettaDocIndexOptions): MettaDocIndex {
  const runtime = options.runtime ?? new CoreRuntime();
  const rootUri = normalizeRootUri(options.workspaceRootUri);
  const sourceRootUri = normalizeRootUri(options.sourceRootUri);
  const hostOperations = hostBindingDocs(options.hostBindings ?? [], sourceRootUri);
  const modules = moduleDocs(options.analyzer, runtime, rootUri, sourceRootUri, hostOperations);
  const fingerprintInput = { modules, hostOperations };
  return {
    schemaVersion: 1,
    generatedAt: options.generatedAt ?? GENERATED_AT,
    sourceFingerprint: stableHash(stableStringify(fingerprintInput)),
    modules,
    hostOperations,
  };
}

function mdEscape(text: string): string {
  return text.replaceAll("\\", "\\\\").replaceAll("|", "\\|");
}

function codeFence(language: string, code: string): string {
  return `\`\`\`${language}\n${code}\n\`\`\``;
}

function sourceText(path: string, range: Range | null): string {
  return range === null ? path : `${path}:${sourceLine(range)}`;
}

function sourceLineBlock(path: string, range: Range | null): string {
  return `Source: \`${sourceText(path, range)}\``;
}

function hostTypescriptSignature(operation: HostOperationDoc): string {
  return `interface HostOperation {\n  ${JSON.stringify(operation.name)}${operation.tsSignature};\n}`;
}

function symbolSection(symbol: MettaSymbolDoc): string {
  const parts = [`### \`${symbol.name}\` {#${symbol.anchor}}`, `Kind: \`${symbol.kind}\``];
  if (symbol.signature.length > 0) parts.push(codeFence("metta", symbol.signature));
  const description =
    symbol.doc?.description && symbol.doc.description.length > 0
      ? symbol.doc.description
      : symbol.fallbackDoc;
  if (description !== null && description.length > 0) parts.push(description);
  if (symbol.doc !== null) parts.push(...docDetailSections(symbol.doc));
  if (symbol.hostOperation !== null)
    parts.push(`Host operation: [\`${symbol.name}\`](../host/${symbol.hostOperation})`);
  parts.push(sourceLineBlock(symbol.sourcePath, symbol.range));
  return parts.join("\n\n");
}

function symbolTable(symbols: readonly MettaSymbolDoc[]): string {
  if (symbols.length === 0) return "";
  const rows = symbols.map((symbol) => {
    const type = symbol.type.length > 0 ? `\`${mdEscape(symbol.type)}\`` : "";
    return `| [\`${mdEscape(symbol.name)}\`](#${symbol.anchor}) | ${symbol.kind} | ${type} |`;
  });
  return ["| Symbol | Kind | Type |", "|---|---|---|", ...rows].join("\n");
}

function moduleImports(imports: readonly string[]): string {
  if (imports.length === 0) return "This module has no imports.";
  return imports.map((raw) => `- \`${raw}\``).join("\n");
}

export function renderMettaModulePage(module: MettaModuleDoc): string {
  const sections = [
    GENERATED_NOTE,
    `# ${module.name}`,
    sourceLineBlock(module.sourcePath, null),
    "## Imports",
    moduleImports(module.imports),
  ];
  if (module.symbols.length > 0) {
    sections.push("## Symbols", symbolTable(module.symbols));
    for (const kind of SYMBOL_KIND_ORDER) {
      const symbols = module.symbols.filter((symbol) => symbol.kind === kind);
      if (symbols.length === 0) continue;
      sections.push(`## ${SYMBOL_KIND_TITLES[kind]}`, ...symbols.map(symbolSection));
    }
  } else {
    sections.push("## Symbols", "This module declares no public symbols.");
  }
  return `${sections.join("\n\n")}\n`;
}

function moduleTable(modules: readonly MettaModuleDoc[]): string {
  if (modules.length === 0) return "No MeTTa modules were indexed.";
  const rows = modules.map((module) => {
    const symbolCount = String(module.symbols.length);
    return `| [${mdEscape(module.name)}](modules/${module.slug}) | ${symbolCount} | \`${mdEscape(module.sourcePath)}\` |`;
  });
  return ["| Module | Symbols | Source |", "|---|---:|---|", ...rows].join("\n");
}

function hostTable(operations: readonly HostOperationDoc[]): string {
  if (operations.length === 0) return "No TypeScript host operations were indexed.";
  const rows = operations.map(
    (operation) =>
      `| [\`${mdEscape(operation.name)}\`](host/${operation.slug}) | ${operation.hostKind} | \`${mdEscape(operation.mettaType)}\` | \`${mdEscape(operation.origin)}\` |`,
  );
  return ["| Operation | Kind | MeTTa type | Origin |", "|---|---|---|---|", ...rows].join("\n");
}

export function renderMettaDocsIndexPage(index: MettaDocIndex): string {
  return `${[
    GENERATED_NOTE,
    "# MeTTa API reference",
    "This reference is generated from MeTTa definitions, `@doc` atoms, `;;` doc comments, and TypeScript grounded-operation signatures.",
    `Source fingerprint: \`${index.sourceFingerprint}\``,
    "## Modules",
    moduleTable(index.modules),
    "## TypeScript host operations",
    hostTable(index.hostOperations),
  ].join("\n\n")}\n`;
}

export function renderHostOperationPage(operation: HostOperationDoc): string {
  const sections = [
    GENERATED_NOTE,
    `# \`${operation.name}\``,
    `Kind: \`${operation.hostKind}\``,
    codeFence("metta", `(: ${operation.name} ${operation.mettaType})`),
    codeFence("ts", hostTypescriptSignature(operation)),
  ];
  if (operation.docs.length > 0) sections.push(operation.docs);
  sections.push(sourceLineBlock(operation.sourcePath, operation.definitionRange));
  return `${sections.join("\n\n")}\n`;
}

export function renderMettaDocsJson(index: MettaDocIndex): string {
  return `${JSON.stringify(index, null, 2)}\n`;
}

function sidebarEntry(text: string, link: string): string {
  return `{ text: ${JSON.stringify(text)}, link: ${JSON.stringify(link)} }`;
}

function sidebarGroup(text: string, collapsed: boolean, entries: readonly string[]): string {
  return [
    `{`,
    `  text: ${JSON.stringify(text)},`,
    `  collapsed: ${collapsed ? "true" : "false"},`,
    `  items: [`,
    entries.map((entry) => `    ${entry},`).join("\n"),
    `  ],`,
    `}`,
  ].join("\n");
}

export function renderMettaSidebarModule(index: MettaDocIndex): string {
  const moduleEntries = index.modules.map((module) =>
    sidebarEntry(module.name, `/reference/metta/modules/${module.slug}`),
  );
  const hostEntries = index.hostOperations.map((operation) =>
    sidebarEntry(operation.name, `/reference/metta/host/${operation.slug}`),
  );
  const groups = [
    sidebarEntry("Overview", "/reference/metta/"),
    sidebarGroup("Modules", true, moduleEntries),
    sidebarGroup("Host operations", true, hostEntries),
  ];
  return [
    "// SPDX-FileCopyrightText: 2026 MesTTo",
    "// SPDX-License-Identifier: Apache-2.0",
    "// Generated by scripts/generate-metta-docs.mjs. Do not edit by hand.",
    "",
    "export const mettaApiSidebar = {",
    '  text: "MeTTa API",',
    "  collapsed: false,",
    "  items: [",
    groups.map((group) => `    ${group.replaceAll("\n", "\n    ")},`).join("\n"),
    "  ],",
    "} as const;",
    "",
  ].join("\n");
}

export function mettaModuleOutputPath(module: MettaModuleDoc): string {
  return `${module.slug}.md`;
}

export function hostOperationOutputPath(operation: HostOperationDoc): string {
  return `${operation.slug}.md`;
}
