// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/bundle-browser-ide.mjs. Do not edit manually.

export const BROWSER_WORKER_BUILD_ID = "c68de0cc5756eed1e5c192850b543f10d6a2be9a1dc952dd385f352e2815e1e7";
