// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/bundle-browser-ide.mjs. Do not edit manually.

export const BROWSER_WORKER_BUILD_ID = "0544465aa92201a8ccc211d2d566907f59b035c91f9d6407625422764e651e20";
