// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/bundle-browser-ide.mjs. Do not edit manually.

export const BROWSER_WORKER_BUILD_ID = "df78dbb5c83c0095aa3c90ae0b371e2b7e2a9d43323ca3bf9ab6822414df59f2";
