// SPDX-FileCopyrightText: 2026 MesTTo
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-metta-docs.mjs. Do not edit by hand.

export const mettaApiSidebar = {
  text: "MeTTa API",
  collapsed: false,
  items: [
    { text: "Overview", link: "/reference/metta/" },
    {
      text: "Modules",
      collapsed: true,
      items: [
        { text: "01-hovers", link: "/reference/metta/modules/01-hovers" },
        { text: "02-running", link: "/reference/metta/modules/02-running" },
        { text: "03-python", link: "/reference/metta/modules/03-python" },
        { text: "04-diagnostics", link: "/reference/metta/modules/04-diagnostics" },
        { text: "05-lint-and-suppression/demo", link: "/reference/metta/modules/05-lint-and-suppression/demo" },
        { text: "06-type-suggestions", link: "/reference/metta/modules/06-type-suggestions" },
        { text: "07-pseudocode", link: "/reference/metta/modules/07-pseudocode" },
        { text: "08-navigation", link: "/reference/metta/modules/08-navigation" },
        { text: "09-formatting", link: "/reference/metta/modules/09-formatting" },
        { text: "10-testing", link: "/reference/metta/modules/10-testing" },
        { text: "11-modules/geometry", link: "/reference/metta/modules/11-modules/geometry" },
        { text: "11-modules/lib/vectors", link: "/reference/metta/modules/11-modules/lib/vectors" },
        { text: "11-modules/main", link: "/reference/metta/modules/11-modules/main" },
        { text: "12-completion-and-hints", link: "/reference/metta/modules/12-completion-and-hints" },
        { text: "13-trace", link: "/reference/metta/modules/13-trace" },
        { text: "14-editor-surfaces", link: "/reference/metta/modules/14-editor-surfaces" },
        { text: "15-guarded-and-agent-surfaces", link: "/reference/metta/modules/15-guarded-and-agent-surfaces" },
        { text: "16-debugging", link: "/reference/metta/modules/16-debugging" },
        { text: "17-prolog-diagnostics/main", link: "/reference/metta/modules/17-prolog-diagnostics/main" },
        { text: "18-host-bridge/main", link: "/reference/metta/modules/18-host-bridge/main" },
        { text: "math", link: "/reference/metta/modules/math" },
      ],
    },
    {
      text: "Host operations",
      collapsed: true,
      items: [
        { text: "my-max", link: "/reference/metta/host/my-max" },
      ],
    },
  ],
} as const;
